name = "hk-homework-check"
main = "src/worker.js"
compatibility_date = "2024-09-01"

[assets]
directory = "./website"
binding = "ASSETS"

[[secrets_store_secrets]]
binding = "ANTHROPIC_API_KEY"
store_id = "50b964b41eeb46d3bd4be77e059d3324"
secret_name = "Nn"
